[phases.setup]
aptPkgs = [
  "php-mysql",
  "php-xml",
  "php-mbstring",
  "php-zip",
  "php-gd",
  "php-curl",
  "php-bcmath",
  "php-intl"
]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache"
]

[phases.start]
cmd = "php -d variables_order=EGPCS -S 0.0.0.0:8080 -t public"
